### ISSUE TITLE
bottom microswitch cant work

### ISSUE THREAD

**Issue by jerem1973** [IRTrail/G2E-Filametrix#8]
![2024-03-12 17_01_55-_Sans titre - SuperSlicer_2 4  based on PrusaSlicer](https://github.com/IRTrail/G2E-Filametrix/assets/16267279/d58175a9-fb9e-481e-b1fe-bc0a13a7f594)
the rolling ball does not go far enough into the filament passage.
result the ball presses on the microswitch without filament engaged
apart from the detail very nice work

**Comment by IRTrail** [comment]
99% of these types of issues come down to print quality. The switches have half a millimeter range of actuation, which is very difficult to attain on a 3D printer. Thus, the print quality must be very good to attain reliable operation.

During the creation of this model, there was special attention paid to ensuring both switch cavities were the same distance from the centerline of the filament path. Given that only the lower switch is causing you issues and the upper is working well, I am inclined to think the issue is print quality in this case as well.

I would suggest re-reading the directions, paying special attention to the part where it says to print KinematiDigit's calibration cube first. You can use the Ellis print guide to help you tune your printer such that the calibration cube passes all the tests.
